### ISSUE TITLE
这博客是你自己写的吗

### ISSUE THREAD

**Issue by bvcalf** [eson15/Blog#3]
这不是人家java1234站长写的吗，你这直接把logo一抹拿来当成自己写的啦？

**Comment by eson15** [comment]
不是 我是看了他的视频的 然后修改了一些东西 他的源码是开源的 我修改的地方有首页部分、评论部分、表的关联、博客内容详细显示部分、添加了几个功能，比如相册模块（还没写好）、资源共享、分享功能我用的是百度的、还有一些后台程序的优化，因为峰哥那个源码还是有很多小bug的，上面提到的这些，我都有和峰哥讨论过。您仔细阅读一下源码就能发现我说的这些东西，要知道，搞清楚一个东西话，仅仅靠拷贝是不行滴。
